
rpgoCPpref = {
	["enabled"] = true,
	["honorold"] = true,
	["debug"] = false,
	["questsfull"] = false,
	["tooltipshtml"] = true,
	["lite"] = true,
	["scan"] = {
		["inventory"] = true,
		["talents"] = true,
		["honor"] = true,
		["reputation"] = true,
		["spells"] = true,
		["pet"] = true,
		["equipment"] = true,
		["mail"] = true,
		["professions"] = true,
		["skills"] = true,
		["quests"] = true,
		["bank"] = true,
	},
	["ver"] = 10500,
	["reagenthtml"] = true,
	["talentsfull"] = true,
}
myProfile = {
	["Kronos"] = {
		["Malyg"] = {
			["Ranged Attack"] = {
				["AttackSpeed"] = "1.90",
				["AttackDPS"] = "62.6",
				["HasWandEquipped"] = true,
				["DamageRangeBase"] = "83:155",
				["AttackRating"] = 300,
				["DamageRangeTooltip"] = "Ranged<br>Attack Speed (seconds):	1.90<br>Damage:	83 - 155<br>Damage per Second:	62.6",
				["DamageRange"] = "83:155",
			},
			["MailDateUTC"] = "12/22/19 21:32:57",
			["Melee Attack"] = {
				["AttackPower"] = 30,
				["AttackSpeed"] = "2.70",
				["AttackDPS"] = "55.7",
				["DamageRangeBase"] = "121:180",
				["AttackPower2"] = "30:30:0:0",
				["AttackRating"] = 167,
				["AttackPowerTooltip"] = "Increases damage with melee weapons by 2.1 damage per second.",
				["DamageRangeTooltip"] = "Main Hand<br>Attack Speed (seconds):	2.70<br>Damage:	121 - 180<br>Damage per Second:	55.7",
				["AttackPowerDPS"] = "2.1",
				["DamageRange"] = "121:180",
			},
			["Mana"] = 5023,
			["Locale"] = "enUS",
			["Race"] = "Gnome",
			["CritPercent"] = "2.65",
			["CPversion"] = "1.6.3",
			["MitigationPercent"] = "11.29",
			["MailBox"] = {
			},
			["SubZone"] = "",
			["RaceEn"] = "Gnome",
			["Experience"] = "224:0",
			["DateUTC"] = "12/24/19 23:54:59",
			["Reputation"] = {
				["Other"] = {
					["Wildhammer Clan"] = {
						["Standing"] = "Neutral",
						["Value"] = "1290/3000",
						["AtWar"] = 0,
					},
					["Thorium Brotherhood"] = {
						["Standing"] = "Neutral",
						["Value"] = "700/3000",
						["AtWar"] = 0,
					},
					["Gelkis Clan Centaur"] = {
						["Standing"] = "Hated",
						["Value"] = "35600/36000",
						["AtWar"] = 1,
					},
					["Bloodsail Buccaneers"] = {
						["Standing"] = "Hated",
						["Value"] = "23715/36000",
						["AtWar"] = 1,
					},
					["Brood of Nozdormu"] = {
						["Standing"] = "Hated",
						["Value"] = "1800/36000",
						["AtWar"] = 1,
					},
					["Zandalar Tribe"] = {
						["Standing"] = "Honored",
						["Value"] = "3531/12000",
						["AtWar"] = 0,
					},
					["Timbermaw Hold"] = {
						["Standing"] = "Unfriendly",
						["Value"] = "1275/3000",
						["AtWar"] = 0,
					},
					["Hydraxian Waterlords"] = {
						["Standing"] = "Neutral",
						["Value"] = "685/3000",
						["AtWar"] = 0,
					},
					["Shen'dralar"] = {
						["Standing"] = "Neutral",
						["Value"] = "1000/3000",
						["AtWar"] = 0,
					},
					["Magram Clan Centaur"] = {
						["Standing"] = "Friendly",
						["Value"] = "830/6000",
						["AtWar"] = 0,
					},
					["Cenarion Circle"] = {
						["Standing"] = "Honored",
						["Value"] = "2150/12000",
						["AtWar"] = 1,
					},
					["Argent Dawn"] = {
						["Standing"] = "Revered",
						["Value"] = "2795/21000",
						["AtWar"] = 0,
					},
				},
				["Alliance Forces"] = {
					["The League of Arathor"] = {
						["Standing"] = "Neutral",
						["Value"] = "0/3000",
						["AtWar"] = 0,
					},
					["Silverwing Sentinels"] = {
						["Standing"] = "Neutral",
						["Value"] = "0/3000",
						["AtWar"] = 0,
					},
				},
				["Count"] = 26,
				["Steamwheedle Cartel"] = {
					["Gadgetzan"] = {
						["Standing"] = "Honored",
						["Value"] = "3053/12000",
						["AtWar"] = 0,
					},
					["Booty Bay"] = {
						["Standing"] = "Honored",
						["Value"] = "3987/12000",
						["AtWar"] = 0,
					},
					["Ratchet"] = {
						["Standing"] = "Friendly",
						["Value"] = "1897/6000",
						["AtWar"] = 0,
					},
					["Everlook"] = {
						["Standing"] = "Friendly",
						["Value"] = "4322/6000",
						["AtWar"] = 0,
					},
				},
				["Alliance"] = {
					["Stormwind"] = {
						["Standing"] = "Exalted",
						["Value"] = "999/1000",
						["AtWar"] = 0,
					},
					["Ironforge"] = {
						["Standing"] = "Revered",
						["Value"] = "10838/21000",
						["AtWar"] = 0,
					},
					["Gnomeregan Exiles"] = {
						["Standing"] = "Revered",
						["Value"] = "5676/21000",
						["AtWar"] = 0,
					},
					["Darnassus"] = {
						["Standing"] = "Revered",
						["Value"] = "7410/21000",
						["AtWar"] = 0,
					},
				},
			},
			["Stats"] = {
				["Intellect"] = "131:262:131:0",
				["Defense"] = "300:300:0:0",
				["Strength"] = "40:40:0:0",
				["Agility"] = "53:53:0:0",
				["Armor"] = "700:700:0:0",
				["Spirit"] = "107:139:32:0",
				["Stamina"] = "88:189:101:0",
			},
			["FactionEn"] = "Alliance",
			["HasRelicSlot"] = false,
			["Equipment"] = {
				["Waist"] = {
					["Name"] = "Felheart Belt",
					["Color"] = "ffa335ee",
					["Tooltip"] = "Felheart Belt<br>Soulbound<br>Waist	Cloth<br>57 Armor<br>+18 Stamina<br>+15 Intellect<br>+8 Spirit<br>+7 Fire Resistance<br>Durability 35 / 35<br>Classes: Warlock<br>Requires Level 60<br>Equip: Increases damage and healing done by magical spells and effects by up to 20.<br> <br><br>Felheart Raiment (1/8)<br>  Felheart Belt<br>  Felheart Bracers<br>  Felheart Gloves<br>  Felheart Pants<br>  Felheart Robes<br>  Felheart Shoulder Pads<br>  Felheart Horns<br>  Felheart Slippers<br> <br><br>(3) Set: Health or Mana gained from Drain Life and Drain Mana increased by 15%.<br>(5) Set: Your pet gains 15 stamina and 100 spell resistance against all schools of magic.<br>(8) Set: Mana cost of Shadow spells reduced by 15%.",
					["Item"] = "16806:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Belt_13",
				},
				["Finger0"] = {
					["Name"] = "Ring of Unspoken Names",
					["Color"] = "ffa335ee",
					["Tooltip"] = "Ring of Unspoken Names<br>Soulbound<br>Unique<br>Finger<br>+12 Stamina<br>Classes: Warlock<br>Requires Level 60<br>Equip: Improves your chance to get a critical strike with spells by 1%.<br>Equip: Increases damage and healing done by magical spells and effects by up to 14.<br>Equip: Improves your chance to hit with spells by 1%.<br> <br><br>Implements of Unspoken Names (1/3)<br>  Kris of Unspoken Names<br>  Ring of Unspoken Names<br>  Shroud of Unspoken Names<br> <br><br>(3) Set: 5% increased damage from your summoned pets' melee attacks and damage spells.",
					["Item"] = "21417:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Jewelry_Ring_AhnQiraj_03",
				},
				["Neck"] = {
					["Name"] = "Kezan's Taint",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Kezan's Taint<br>Soulbound<br>Unique<br>Neck<br>+10 Stamina<br>+6 Intellect<br>Classes: Warlock<br>Equip: Increases damage and healing done by magical spells and effects by up to 12.",
					["Item"] = "19603:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Jewelry_Necklace_24",
				},
				["Trinket0"] = {
					["Name"] = "Eye of the Beast",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Eye of the Beast<br>Soulbound<br>Trinket<br>Classes: Priest, Shaman, Mage, Warlock, Druid<br>Equip: Improves your chance to get a critical strike with spells by 2%.",
					["Item"] = "13968:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Jewelry_Talisman_08",
				},
				["Back"] = {
					["Name"] = "Cloak of the Hakkari Worshipers",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Cloak of the Hakkari Worshipers<br>Soulbound<br>Back<br>48 Armor<br>+6 Stamina<br>+6 Intellect<br>Requires Level 60<br>Equip: Increases damage and healing done by magical spells and effects by up to 23.",
					["Item"] = "22711:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Misc_Cape_16",
				},
				["Shirt"] = {
					["Name"] = "Captain Sander's Shirt",
					["Color"] = "ffffffff",
					["Tooltip"] = "Captain Sander's Shirt<br>Soulbound<br>Shirt",
					["Item"] = "3342:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Shirt_14",
				},
				["Hands"] = {
					["Name"] = "Bloodtinged Gloves",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Bloodtinged Gloves<br>Soulbound<br>Hands	Cloth<br>62 Armor<br>+10 Stamina<br>+10 Intellect<br>+10 Spirit<br>Skinning +5<br>Durability 30 / 30<br>Requires Level 60<br>Equip: Increases damage and healing done by magical spells and effects by up to 19.<br>Equip: Improves your chance to hit with spells by 1%.",
					["Item"] = "19929:865:0:0",
					["Texture"] = "Interface\\Icons\\INV_Gauntlets_16",
				},
				["Wrist"] = {
					["Name"] = "Zandalar Demoniac's Wraps",
					["Color"] = "ffa335ee",
					["Tooltip"] = "Zandalar Demoniac's Wraps<br>Soulbound<br>Wrist	Cloth<br>41 Armor<br>+15 Stamina<br>+8 Intellect<br>Durability 35 / 35<br>Classes: Warlock<br>Equip: Increases damage and healing done by magical spells and effects by up to 16.<br> <br><br>Demoniac's Threads (1/5)<br>  Kezan's Unstoppable Taint<br>  Hazza'rah's Charm of Destruction<br>  Zandalar Demoniac's Wraps<br>  Zandalar Demoniac's Mantle<br>  Zandalar Demoniac's Robe<br> <br><br>(2) Set: Increases damage and healing done by magical spells and effects by up to 12.<br>(3) Set: Increases the damage of Corruption by 2%.<br>(5) Set: Decreases the cooldown of Death Coil by 15%.",
					["Item"] = "19848:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Bracer_07",
				},
				["Trinket1"] = {
					["Name"] = "Briarwood Reed",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Briarwood Reed<br>Soulbound<br>Unique<br>Trinket<br>Requires Level 55<br>Equip: Increases damage and healing done by magical spells and effects by up to 29.",
					["Item"] = "12930:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Misc_Root_02",
				},
				["Head"] = {
					["Name"] = "Spellweaver's Turban",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Spellweaver's Turban<br>Soulbound<br>Head	Cloth<br>73 Armor<br>+9 Intellect<br>Durability 50 / 50<br>Requires Level 60<br>Equip: Increases damage and healing done by magical spells and effects by up to 36.<br>Equip: Improves your chance to hit with spells by 1%.",
					["Item"] = "22267:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Helmet_62",
				},
				["Finger1"] = {
					["Name"] = "Band of Servitude",
					["Color"] = "ffa335ee",
					["Tooltip"] = "Band of Servitude<br>Soulbound<br>Unique<br>Finger<br>+8 Stamina<br>+9 Intellect<br>Requires Level 60<br>Equip: Increases damage and healing done by magical spells and effects by up to 23.",
					["Item"] = "22721:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Jewelry_Ring_16",
				},
				["Chest"] = {
					["Name"] = "Bloodvine Vest",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Bloodvine Vest<br>Soulbound<br>Chest	Cloth<br>92 Armor<br>+13 Intellect<br>Durability 80 / 80<br>Requires Level 60<br>Equip: Improves your chance to hit with spells by 2%.<br>Equip: Increases damage and healing done by magical spells and effects by up to 27.<br> <br><br>Bloodvine Garb (3/3)<br>Requires Tailoring (300)<br>  Bloodvine Vest<br>  Bloodvine Leggings<br>  Bloodvine Boots<br> <br><br>(3) Set: Improves your chance to get a critical strike with spells by 2%.<br>|cff00ff00<Made by Naitsirhc>|r",
					["Item"] = "19682:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Chest_Cloth_07",
				},
				["Tabard"] = {
					["Name"] = "Tabard of the Scarlet Crusade",
					["Color"] = "ffffffff",
					["Tooltip"] = "Tabard of the Scarlet Crusade<br>Soulbound<br>Unique<br>Tabard",
					["Item"] = "23192:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Misc_Cape_18",
				},
				["Ranged"] = {
					["Name"] = "Bonecreeper Stylus",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Bonecreeper Stylus<br>Soulbound<br>Wand<br>83 - 155 Arcane Damage	Speed 1.90<br>(62.6 damage per second)<br>+4 Intellect<br>Durability 65 / 65<br>Requires Level 57<br>Equip: Increases damage and healing done by magical spells and effects by up to 11.",
					["Item"] = "13938:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Misc_Bone_TaurenSkull_01",
				},
				["MainHand"] = {
					["Name"] = "Rod of the Ogre Magi",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Rod of the Ogre Magi<br>Soulbound<br>Two-Hand	Staff<br>116 - 175 Damage	Speed 2.70<br>(53.9 damage per second)<br>+11 Stamina<br>+14 Intellect<br>+7 Spirit<br>Durability 100 / 100<br>Requires Level 58<br>Equip: Improves your chance to get a critical strike with spells by 1%.<br>Equip: Increases damage and healing done by magical spells and effects by up to 23.",
					["Item"] = "18534:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Staff_32",
				},
				["Legs"] = {
					["Name"] = "Bloodvine Leggings",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Bloodvine Leggings<br>Soulbound<br>Legs	Cloth<br>80 Armor<br>+6 Intellect<br>Durability 65 / 65<br>Requires Level 60<br>Equip: Improves your chance to hit with spells by 1%.<br>Equip: Increases damage and healing done by magical spells and effects by up to 37.<br> <br><br>Bloodvine Garb (3/3)<br>Requires Tailoring (300)<br>  Bloodvine Vest<br>  Bloodvine Leggings<br>  Bloodvine Boots<br> <br><br>(3) Set: Improves your chance to get a critical strike with spells by 2%.<br>|cff00ff00<Made by Naitsirhc>|r",
					["Item"] = "19683:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Pants_Cloth_14",
				},
				["Shoulder"] = {
					["Name"] = "Mantle of Maz'Nadir",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Mantle of Maz'Nadir<br>Soulbound<br>Shoulder	Cloth<br>78 Armor<br>+11 Stamina<br>+15 Intellect<br>+7 Spirit<br>Durability 50 / 50<br>Requires Level 60<br>Equip: Increases damage and healing done by magical spells and effects by up to 21.",
					["Item"] = "21468:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Shoulder_25",
				},
				["Feet"] = {
					["Name"] = "Bloodvine Boots",
					["Color"] = "ff0070dd",
					["Tooltip"] = "Bloodvine Boots<br>Soulbound<br>Feet	Cloth<br>63 Armor<br>+16 Intellect<br>Mithril Spurs<br>Durability 40 / 40<br>Requires Level 60<br>Equip: Improves your chance to hit with spells by 1%.<br>Equip: Increases damage and healing done by magical spells and effects by up to 19.<br> <br><br>Bloodvine Garb (3/3)<br>Requires Tailoring (300)<br>  Bloodvine Vest<br>  Bloodvine Leggings<br>  Bloodvine Boots<br> <br><br>(3) Set: Improves your chance to get a critical strike with spells by 2%.<br>|cff00ff00<Made by Naitsirhc>|r",
					["Item"] = "19684:464:0:0",
					["Texture"] = "Interface\\Icons\\INV_Boots_Cloth_02",
				},
			},
			["Class"] = "Warlock",
			["Health"] = 3124,
			["Faction"] = "Alliance",
			["BlockPercent"] = "0.00",
			["timestamp"] = {
				["Inventory"] = 1577231699,
				["init"] = {
					["TimeStamp"] = 1577231699,
					["Date"] = "12/25/19 00:54:59",
					["ServerTime"] = "00:54",
					["DateUTC"] = "12/24/19 23:54:59",
				},
				["Equipment"] = 1577231577,
				["Pets"] = {
					["Graz'vhug"] = 1577145440,
				},
				["MailBox"] = 1577050377,
				["Stats"] = 1577231699,
				["Bank"] = 1574204249,
			},
			["Quests"] = {
				["Azshara"] = {
					[1] = {
						["Title"] = "The Molten Core",
						["Tasks"] = {
							[1] = {
								["Type"] = "monster",
								["Note"] = "Molten Giant slain: 0/1",
							},
							[2] = {
								["Type"] = "monster",
								["Note"] = "Firelord slain: 0/1",
							},
							[3] = {
								["Type"] = "monster",
								["Note"] = "Ancient Core Hound slain: 0/1",
							},
							[4] = {
								["Type"] = "monster",
								["Note"] = "Lava Surger slain: 0/1",
							},
						},
						["Level"] = 60,
						["RewardMoney"] = 5970,
						["Tag"] = "Raid",
					},
				},
				["Zul'Gurub"] = {
					[2] = {
						["Title"] = "A Bijou for Zanza",
						["RewardMoney"] = 21960,
						["Rewards"] = {
							[1] = {
								["Quantity"] = 1,
								["Name"] = "Zandalar Honor Token",
								["Color"] = "ff1eff00",
								["Tooltip"] = "Zandalar Honor Token<br>Binds when picked up<br>Use: Increase your reputation permanently with the Zandalar Tribe.",
								["Item"] = "19858:0:0:0",
								["Texture"] = "Interface\\Icons\\INV_Misc_Coin_08",
							},
						},
						["Level"] = 60,
					},
				},
			},
			["Guild"] = {
				["Title"] = "Lead Alt",
				["GuildName"] = "Legacy",
				["Name"] = "Legacy",
				["Rank"] = 3,
			},
			["Inventory"] = {
				["Bag5"] = {
					["Item"] = "0:0:0:0",
					["Contents"] = {
						[1] = {
							["Quantity"] = 1,
							["Name"] = "The Scarlet Key",
							["Color"] = "ff1eff00",
							["Tooltip"] = "",
							["Item"] = "7146:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_01",
						},
						[2] = {
							["Quantity"] = 1,
							["Name"] = "Hexx's Key",
							["Color"] = "ffffffff",
							["Tooltip"] = "",
							["Item"] = "9472:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_01",
						},
						[3] = {
							["Quantity"] = 1,
							["Name"] = "Skeleton Key",
							["Color"] = "ffffffff",
							["Tooltip"] = "",
							["Item"] = "13704:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_11",
						},
						[4] = {
							["Quantity"] = 4,
							["Name"] = "Relic Coffer Key",
							["Color"] = "ffffffff",
							["Tooltip"] = "",
							["Item"] = "11078:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_03",
						},
						[5] = {
							["Quantity"] = 1,
							["Name"] = "Shadowforge Key",
							["Color"] = "ffffffff",
							["Tooltip"] = "",
							["Item"] = "11000:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_08",
						},
						[6] = {
							["Quantity"] = 1,
							["Name"] = "Gordok Shackle Key",
							["Color"] = "ff1eff00",
							["Tooltip"] = "",
							["Item"] = "18250:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_11",
						},
						[7] = {
							["Quantity"] = 1,
							["Name"] = "Crescent Key",
							["Color"] = "ffffffff",
							["Tooltip"] = "",
							["Item"] = "18249:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Key_10",
						},
					},
					["Color"] = "ffffffff",
					["Tooltip"] = "Keyring<br>12 Slot Keyring",
					["Slots"] = 12,
					["Texture"] = "Interface\\Buttons\\UI-Button-KeyRing",
				},
				["Bag4"] = {
					["Contents"] = {
						[1] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[2] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[3] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[4] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[5] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[6] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[7] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[8] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[9] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[10] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[11] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[12] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[13] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[14] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[15] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[16] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[17] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[18] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[19] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
						[20] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
					},
					["Color"] = "ff1eff00",
					["Tooltip"] = "Soul Pouch<br>Soulbound<br>20 Slot Soul Bag<br>Classes: Warlock<br>|cff00ff00<Made by Naitsirhc>|r",
					["Slots"] = 20,
					["Item"] = "21340:0:0:0",
					["Name"] = "Soul Pouch",
					["Texture"] = "Interface\\Icons\\INV_Misc_Bag_Soulbag",
				},
				["Bag0"] = {
					["Contents"] = {
						[16] = {
							["Quantity"] = 1,
							["Name"] = "Soul Shard",
							["Color"] = "ffffffff",
							["Tooltip"] = "Soul Shard<br>Soulbound",
							["Item"] = "6265:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Amethyst_02",
						},
					},
					["Color"] = "ffffffff",
					["Tooltip"] = "Backpack<br>16 Slot ",
					["Slots"] = 16,
					["Item"] = "0:0:0:0",
					["Name"] = "Backpack",
					["Texture"] = "Interface\\Buttons\\Button-Backpack-Up",
				},
				["Bag1"] = {
					["Contents"] = {
						[1] = {
							["Quantity"] = 1,
							["Name"] = "Cenarion Beacon",
							["Color"] = "ffffffff",
							["Tooltip"] = "Cenarion Beacon<br>Quest Item<br>Unique<br>\"This device helps identify corrupted elements of nature.\"",
							["Item"] = "11511:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Lantern_01",
						},
						[2] = {
							["Quantity"] = 100,
							["Name"] = "Cenarion Plant Salve",
							["Color"] = "ffffffff",
							["Tooltip"] = "Cenarion Plant Salve<br>Soulbound<br>\"This druidic brew is used to cleanse corrupted plants.\"",
							["Item"] = "11516:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Drink_17",
						},
						[5] = {
							["Quantity"] = 4,
							["Name"] = "Deadwood Headdress Feather",
							["Color"] = "ffffffff",
							["Tooltip"] = "Deadwood Headdress Feather<br>Soulbound<br>\"These may be gathered for the Timbermaw furbolgs to earn their trust.\"",
							["Item"] = "21377:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Feather_13",
						},
						[11] = {
							["Quantity"] = 20,
							["Name"] = "Plaguebloom",
							["Color"] = "ffffffff",
							["Tooltip"] = "Plaguebloom",
							["Item"] = "13466:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_PlagueBloom",
						},
						[12] = {
							["Quantity"] = 20,
							["Name"] = "Thick Leather",
							["Color"] = "ffffffff",
							["Tooltip"] = "Thick Leather",
							["Item"] = "4304:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_LeatherScrap_08",
						},
						[13] = {
							["Quantity"] = 20,
							["Name"] = "Dreamfoil",
							["Color"] = "ffffffff",
							["Tooltip"] = "Dreamfoil",
							["Item"] = "13463:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_DreamFoil",
						},
						[14] = {
							["Quantity"] = 20,
							["Name"] = "Gromsblood",
							["Color"] = "ffffffff",
							["Tooltip"] = "Gromsblood",
							["Item"] = "8846:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_16",
						},
						[15] = {
							["Quantity"] = 20,
							["Name"] = "Dreamfoil",
							["Color"] = "ffffffff",
							["Tooltip"] = "Dreamfoil",
							["Item"] = "13463:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_DreamFoil",
						},
						[16] = {
							["Quantity"] = 5,
							["Name"] = "Mageweave Cloth",
							["Color"] = "ffffffff",
							["Tooltip"] = "Mageweave Cloth",
							["Item"] = "4338:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Fabric_Mageweave_01",
						},
					},
					["Color"] = "ff1eff00",
					["Tooltip"] = "Mooncloth Bag<br>16 Slot Bag<br>|cff00ff00<Made by Naitsirhc>|r",
					["Slots"] = 16,
					["Item"] = "14155:0:0:0",
					["Name"] = "Mooncloth Bag",
					["Texture"] = "Interface\\Icons\\INV_Misc_Bag_14",
				},
				["Bag2"] = {
					["Contents"] = {
						[1] = {
							["Quantity"] = 19,
							["Name"] = "Firebloom",
							["Color"] = "ffffffff",
							["Tooltip"] = "Firebloom",
							["Item"] = "4625:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_19",
						},
						[2] = {
							["Quantity"] = 4,
							["Name"] = "Blindweed",
							["Color"] = "ffffffff",
							["Tooltip"] = "Blindweed",
							["Item"] = "8839:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_14",
						},
						[3] = {
							["Quantity"] = 12,
							["Name"] = "Gromsblood",
							["Color"] = "ffffffff",
							["Tooltip"] = "Gromsblood",
							["Item"] = "8846:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_16",
						},
						[4] = {
							["Quantity"] = 7,
							["Name"] = "Golden Sansam",
							["Color"] = "ffffffff",
							["Tooltip"] = "Golden Sansam",
							["Item"] = "13464:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_SansamRoot",
						},
						[5] = {
							["Quantity"] = 7,
							["Name"] = "Icecap",
							["Color"] = "ffffffff",
							["Tooltip"] = "Icecap",
							["Item"] = "13467:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_IceCap",
						},
						[6] = {
							["Quantity"] = 10,
							["Name"] = "Dreamfoil",
							["Color"] = "ffffffff",
							["Tooltip"] = "Dreamfoil",
							["Item"] = "13463:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_DreamFoil",
						},
						[7] = {
							["Quantity"] = 1,
							["Name"] = "Plaguebloom",
							["Color"] = "ffffffff",
							["Tooltip"] = "Plaguebloom",
							["Item"] = "13466:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_PlagueBloom",
						},
						[8] = {
							["Quantity"] = 19,
							["Name"] = "Mountain Silversage",
							["Color"] = "ffffffff",
							["Tooltip"] = "Mountain Silversage",
							["Item"] = "13465:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_MountainSilverSage",
						},
						[9] = {
							["Quantity"] = 2,
							["Name"] = "Goldthorn",
							["Color"] = "ffffffff",
							["Tooltip"] = "Goldthorn",
							["Item"] = "3821:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Herb_15",
						},
						[12] = {
							["Quantity"] = 1,
							["Name"] = "Heavy Weave Gloves",
							["Color"] = "ffffffff",
							["Tooltip"] = "Heavy Weave Gloves<br>Hands	Cloth<br>18 Armor<br>Minor Mount Speed Increase<br>Durability 20 / 20<br>Requires Level 12",
							["Item"] = "839:930:0:0",
							["Texture"] = "Interface\\Icons\\INV_Gauntlets_18",
						},
						[13] = {
							["Quantity"] = 10,
							["Name"] = "Thick Hide",
							["Color"] = "ffffffff",
							["Tooltip"] = "Thick Hide",
							["Item"] = "8169:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_01",
						},
						[15] = {
							["Quantity"] = 17,
							["Name"] = "Rugged Leather",
							["Color"] = "ffffffff",
							["Tooltip"] = "Rugged Leather",
							["Item"] = "8170:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_LeatherScrap_02",
						},
						[16] = {
							["Quantity"] = 2,
							["Name"] = "Rugged Hide",
							["Color"] = "ffffffff",
							["Tooltip"] = "Rugged Hide",
							["Item"] = "8171:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Pelt_Bear_Ruin_02",
						},
					},
					["Color"] = "ff1eff00",
					["Tooltip"] = "Mooncloth Bag<br>16 Slot Bag<br>|cff00ff00<Made by Naitsirhc>|r",
					["Slots"] = 16,
					["Item"] = "14155:0:0:0",
					["Name"] = "Mooncloth Bag",
					["Texture"] = "Interface\\Icons\\INV_Misc_Bag_14",
				},
				["Bag3"] = {
					["Contents"] = {
						[1] = {
							["Quantity"] = 1,
							["Name"] = "Hearthstone",
							["Color"] = "ffffffff",
							["Tooltip"] = "Hearthstone<br>Soulbound<br>Unique<br>Use: Returns you to Gadgetzan.  Speak to an Innkeeper in a different place to change your home location.",
							["Item"] = "6948:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Rune_01",
						},
						[2] = {
							["Quantity"] = 1,
							["Name"] = "Skinning Knife",
							["Color"] = "ffffffff",
							["Tooltip"] = "Skinning Knife<br>One-Hand<br>2 - 5 Damage	Speed 1.60<br>(2.2 damage per second)",
							["Item"] = "7005:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Weapon_ShortBlade_01",
						},
						[3] = {
							["Quantity"] = 1,
							["Name"] = "Carrot on a Stick",
							["Color"] = "ff1eff00",
							["Tooltip"] = "Carrot on a Stick<br>Soulbound<br>Trinket<br>Equip: Increases mount speed by 3%.",
							["Item"] = "11122:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Food_54",
						},
						[4] = {
							["Quantity"] = 18,
							["Name"] = "Heavy Runecloth Bandage",
							["Color"] = "ffffffff",
							["Tooltip"] = "Heavy Runecloth Bandage<br>Requires First Aid (225)<br>Use: Heals 2000 damage over 8 sec.",
							["Item"] = "14530:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Bandage_12",
						},
						[5] = {
							["Quantity"] = 1,
							["Name"] = "Strong Fishing Pole",
							["Color"] = "ffffffff",
							["Tooltip"] = "Strong Fishing Pole<br>Two-Hand	Fishing Pole<br>13 - 21 Damage	Speed 3.00<br>(5.7 damage per second)<br>Durability 25 / 25<br>Requires Level 5<br>Requires Fishing (10)<br>Equip: Increased Fishing +5.",
							["Item"] = "6365:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Fishingpole_02",
						},
						[6] = {
							["Quantity"] = 1,
							["Name"] = "Finkle's Skinner",
							["Color"] = "ff0070dd",
							["Tooltip"] = "Finkle's Skinner<br>Soulbound<br>Main Hand	Dagger<br>37 - 70 Damage	Speed 1.30<br>(41.2 damage per second)<br>Durability 65 / 65<br>Requires Level 58<br>Equip: Skinning +10.<br>Equip: +45 Attack Power when fighting Beasts.<br>\"Property of Finkle Einhorn, Grandmaster Adventurer\"",
							["Item"] = "12709:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Sword_33",
						},
						[7] = {
							["Quantity"] = 1,
							["Name"] = "Rune of the Dawn",
							["Color"] = "ff0070dd",
							["Tooltip"] = "Rune of the Dawn<br>Soulbound<br>Unique<br>Trinket<br>Equip: Increases damage done to Undead by magical spells and effects by up to 48.  It also allows the acquisition of Scourgestones on behalf of the Argent Dawn.",
							["Item"] = "19812:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Rune_06",
						},
						[8] = {
							["Quantity"] = 8,
							["Name"] = "Runecloth",
							["Color"] = "ffffffff",
							["Tooltip"] = "Runecloth",
							["Item"] = "14047:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Fabric_PurpleFire_01",
						},
						[9] = {
							["Quantity"] = 7,
							["Name"] = "Bright Baubles",
							["Color"] = "ffffffff",
							["Tooltip"] = "Bright Baubles<br>Requires Fishing (100)<br>Use: When applied to your fishing pole, increases Fishing by 75 for 10 minutes.",
							["Item"] = "6532:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Variety_02",
						},
						[10] = {
							["Quantity"] = 1,
							["Name"] = "Blood Scythe",
							["Color"] = "ff0070dd",
							["Tooltip"] = "Blood Scythe<br>Soulbound<br>Unique<br>\"Allows an Herbalist to collect Bloodvine from Zul'Gurub Flora when carried.\"",
							["Item"] = "19727:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Weapon_Shortblade_29",
						},
						[11] = {
							["Quantity"] = 1,
							["Name"] = "Zandalarian Hero Charm",
							["Color"] = "ffa335ee",
							["Tooltip"] = "Zandalarian Hero Charm<br>Soulbound<br>Unique<br>Trinket<br>Use: Increases your spell damage by up to 204 and your healing by up to 408 for 20 sec. Every time you cast a spell, the bonus is reduced by 17 spell damage and 34 healing.",
							["Item"] = "19950:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Jewelry_Necklace_13",
						},
						[12] = {
							["Quantity"] = 1,
							["Name"] = "Cache of Mau'ari",
							["Color"] = "ffffffff",
							["Tooltip"] = "Cache of Mau'ari<br>Soulbound<br>Unique",
							["Item"] = "12384:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Jewelry_Necklace_09",
						},
						[13] = {
							["Quantity"] = 5,
							["Name"] = "Major Healing Potion",
							["Color"] = "ffffffff",
							["Tooltip"] = "Major Healing Potion<br>Requires Level 45<br>Use: Restores 1050 to 1750 health.",
							["Item"] = "13446:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Potion_54",
						},
						[14] = {
							["Quantity"] = 5,
							["Name"] = "Major Mana Potion",
							["Color"] = "ffffffff",
							["Tooltip"] = "Major Mana Potion<br>Requires Level 49<br>Use: Restores 1350 to 2250 mana.",
							["Item"] = "13444:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Potion_76",
						},
						[15] = {
							["Quantity"] = 1,
							["Name"] = "Witchblade",
							["Color"] = "ff0070dd",
							["Tooltip"] = "Witchblade<br>Soulbound<br>One-Hand	Dagger<br>45 - 85 Damage	Speed 1.60<br>(40.6 damage per second)<br>+8 Intellect<br>Durability 65 / 65<br>Requires Level 57<br>Equip: Increases damage and healing done by magical spells and effects by up to 14.",
							["Item"] = "13964:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Weapon_ShortBlade_25",
						},
						[16] = {
							["Quantity"] = 1,
							["Name"] = "Spirit of Aquementas",
							["Color"] = "ff1eff00",
							["Tooltip"] = "Spirit of Aquementas<br>Soulbound<br>Held In Off-hand<br>Equip: Increases damage and healing done by magical spells and effects by up to 20.",
							["Item"] = "11904:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Ore_Arcanite_02",
						},
					},
					["Color"] = "ff1eff00",
					["Tooltip"] = "Traveler's Backpack<br>16 Slot Bag",
					["Slots"] = 16,
					["Item"] = "4500:0:0:0",
					["Name"] = "Traveler's Backpack",
					["Texture"] = "Interface\\Icons\\INV_Misc_Bag_08",
				},
			},
			["Talents"] = {
				["Destruction"] = {
					["Aftermath"] = {
						["Location"] = "2:3",
						["Tooltip"] = "Aftermath<br>Rank 0/5<br>Gives your Destruction spells a 2% chance to daze the target for 5 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_Fire",
						["Rank"] = "0:5",
					},
					["Destructive Reach"] = {
						["Location"] = "4:2",
						["Tooltip"] = "Destructive Reach<br>Rank 2/2<br>Increases the range of your Destruction spells by 20%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_CorpseExplode",
						["Rank"] = "2:2",
					},
					["Conflagrate"] = {
						["Location"] = "7:2",
						["Tooltip"] = "Conflagrate<br>Rank 0/1<br>Requires 5 points in Improved Immolate<br>Requires 30 points in Destruction Talents<br>158 Mana	36 yd range<br>Instant cast	10 sec cooldown<br>Ignites a target that is already afflicted by Immolate, dealing 240 to 306 Fire damage and consuming the Immolate spell.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_Fireball",
						["Rank"] = "0:1",
					},
					["Emberstorm"] = {
						["Location"] = "6:3",
						["Tooltip"] = "Emberstorm<br>Rank 0/5<br>Requires 25 points in Destruction Talents<br>Increases the damage done by your Fire spells by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_SelfDestruct",
						["Rank"] = "0:5",
					},
					["Background"] = "Interface\\TalentFrame\\WarlockDestruction",
					["Intensity"] = {
						["Location"] = "4:1",
						["Tooltip"] = "Intensity<br>Rank 0/2<br>Gives you a 35% chance to resist interruption caused by damage while channeling the Rain of Fire, Hellfire or Soul Fire spell.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_LavaSpawn",
						["Rank"] = "0:2",
					},
					["Ruin"] = {
						["Location"] = "5:3",
						["Tooltip"] = "Ruin<br>Rank 1/1<br>Increases the critical strike damage bonus of your Destruction spells by 100%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",
						["Rank"] = "1:1",
					},
					["Improved Shadow Bolt"] = {
						["Location"] = "1:2",
						["Tooltip"] = "Improved Shadow Bolt<br>Rank 5/5<br>Your Shadow Bolt critical strikes increase Shadow damage dealt to the target by 20% until 4 non-periodic damage sources are applied.  Effect lasts a maximum of 12 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ShadowBolt",
						["Rank"] = "5:5",
					},
					["Improved Immolate"] = {
						["Location"] = "5:2",
						["Tooltip"] = "Improved Immolate<br>Rank 0/5<br>Increases the initial damage of your Immolate spell by 5%.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_Immolation",
						["Rank"] = "0:5",
					},
					["Improved Firebolt"] = {
						["Location"] = "3:1",
						["Tooltip"] = "Improved Firebolt<br>Rank 0/2<br>Reduces the casting time of your Imp's Firebolt spell by 0.5 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_FireBolt",
						["Rank"] = "0:2",
					},
					["PointsSpent"] = 23,
					["Devastation"] = {
						["Location"] = "3:3",
						["Tooltip"] = "Devastation<br>Rank 5/5<br>Increases the critical strike chance of your Destruction spells by 5%.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_FlameShock",
						["Rank"] = "5:5",
					},
					["Pyroclasm"] = {
						["Location"] = "5:1",
						["Tooltip"] = "Pyroclasm<br>Rank 0/2<br>Requires 2 points in Intensity<br>Gives your Rain of Fire, Hellfire, and Soul Fire spells a 13% chance to stun the target for 3 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_Volcano",
						["Rank"] = "0:2",
					},
					["Shadowburn"] = {
						["Location"] = "3:4",
						["Tooltip"] = "Shadowburn<br>Rank 1/1<br>100 Mana	24 yd range<br>Instant cast	15 sec cooldown<br>Reagents: Soul Shard<br>Instantly blasts the target for 87 to 99 Shadow damage.  If the target dies within 5 sec of Shadowburn, and yields experience or honor, the caster gains a Soul Shard.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ScourgeBuild",
						["Rank"] = "1:1",
					},
					["Cataclysm"] = {
						["Location"] = "1:3",
						["Tooltip"] = "Cataclysm<br>Rank 4/5<br>Reduces the Mana cost of your Destruction spells by 4%.<br> <br>Next rank:<br>Reduces the Mana cost of your Destruction spells by 5%.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_WindsofWoe",
						["Rank"] = "4:5",
					},
					["Order"] = 3,
					["Bane"] = {
						["Location"] = "2:2",
						["Tooltip"] = "Bane<br>Rank 5/5<br>Reduces the casting time of your Shadow Bolt and Immolate spells by 0.5 sec and your Soul Fire spell by 2 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_DeathPact",
						["Rank"] = "5:5",
					},
					["Improved Searing Pain"] = {
						["Location"] = "4:4",
						["Tooltip"] = "Improved Searing Pain<br>Rank 0/5<br>Increases the critical strike chance of your Searing Pain spell by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Fire_SoulBurn",
						["Rank"] = "0:5",
					},
					["Improved Lash of Pain"] = {
						["Location"] = "3:2",
						["Tooltip"] = "Improved Lash of Pain<br>Rank 0/2<br>Reduces the cooldown of your Succubus' Lash of Pain spell by 3 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_Curse",
						["Rank"] = "0:2",
					},
				},
				["Demonology"] = {
					["Master Demonologist"] = {
						["Location"] = "6:3",
						["Tooltip"] = "Master Demonologist<br>Rank 0/5<br>Requires 5 points in Unholy Power<br>Requires 25 points in Demonology Talents<br>Grants both the Warlock and the summoned demon an effect as long as that demon is active.<br><br>Imp - Reduces threat caused by 4%.<br><br>Voidwalker - Reduces physical damage taken by 2%.<br><br>Succubus - Increases all damage caused by 2%.<br><br>Felhunter - Increases all resistances by .2 per level.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ShadowPact",
						["Rank"] = "0:5",
					},
					["Master Summoner"] = {
						["Location"] = "4:2",
						["Tooltip"] = "Master Summoner<br>Rank 2/2<br>Reduces the casting time of your Imp, Voidwalker, Succubus, and Felhunter Summoning spells by 4 sec and the Mana cost by 40%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ImpPhaseShift",
						["Rank"] = "2:2",
					},
					["Order"] = 2,
					["Demonic Sacrifice"] = {
						["Location"] = "5:2",
						["Tooltip"] = "Demonic Sacrifice<br>Rank 1/1<br>100 yd range<br>Instant<br>When activated, sacrifices your summoned demon to grant you an effect that lasts 30 min.  The effect is canceled if any Demon is summoned.<br><br>Imp: Increases your Fire damage by 15%.<br><br>Voidwalker: Restores 3% of total Health every 4 sec.<br><br>Succubus: Increases your Shadow damage by 15%.<br><br>Felhunter: Restores 2% of total Mana every 4 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_PsychicScream",
						["Rank"] = "1:1",
					},
					["Improved Succubus"] = {
						["Location"] = "3:1",
						["Tooltip"] = "Improved Succubus<br>Rank 0/3<br>Increases the effect of your Succubus' Lash of Pain and Soothing Kiss spells by 10%, and increases the duration of your Succubus' Seduction and Lesser Invisibility spells by 10%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_SummonSuccubus",
						["Rank"] = "0:3",
					},
					["Background"] = "Interface\\TalentFrame\\WarlockSummoning",
					["Improved Voidwalker"] = {
						["Location"] = "2:2",
						["Tooltip"] = "Improved Voidwalker<br>Rank 3/3<br>Increases the effectiveness of your Voidwalker's Torment, Consume Shadows, Sacrifice and Suffering spells by 30%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_SummonVoidWalker",
						["Rank"] = "3:3",
					},
					["Improved Imp"] = {
						["Location"] = "1:2",
						["Tooltip"] = "Improved Imp<br>Rank 3/3<br>Increases the effect of your Imp's Firebolt, Fire Shield, and Blood Pact spells by 30%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_SummonImp",
						["Rank"] = "3:3",
					},
					["Fel Intellect"] = {
						["Location"] = "2:3",
						["Tooltip"] = "Fel Intellect<br>Rank 1/5<br>Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 3%.<br> <br>Next rank:<br>Increases the maximum Mana of your Imp, Voidwalker, Succubus, and Felhunter by 6%.",
						["Texture"] = "Interface\\Icons\\Spell_Holy_MagicalSentry",
						["Rank"] = "1:5",
					},
					["Improved Healthstone"] = {
						["Location"] = "1:1",
						["Tooltip"] = "Improved Healthstone<br>Rank 2/2<br>Increases the amount of Health restored by your Healthstone by 20%.",
						["Texture"] = "Interface\\Icons\\INV_Stone_04",
						["Rank"] = "2:2",
					},
					["Improved Health Funnel"] = {
						["Location"] = "2:1",
						["Tooltip"] = "Improved Health Funnel<br>Rank 0/2<br>Increases the amount of Health transferred by your Health Funnel spell by 10%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_LifeDrain",
						["Rank"] = "0:2",
					},
					["PointsSpent"] = 21,
					["Improved Spellstone"] = {
						["Location"] = "7:3",
						["Tooltip"] = "Improved Spellstone<br>Rank 0/2<br>Requires 30 points in Demonology Talents<br>Increases the amount of damage absorbed by your Spellstone by 15%.",
						["Texture"] = "Interface\\Icons\\INV_Misc_Gem_Sapphire_01",
						["Rank"] = "0:2",
					},
					["Soul Link"] = {
						["Location"] = "7:2",
						["Tooltip"] = "Soul Link<br>Rank 0/1<br>Requires 30 points in Demonology Talents<br>274 Mana	100 yd range<br>Instant cast<br>When active, 30% of all damage taken by the caster is taken by your Imp, Voidwalker, Succubus, or Felhunter demon instead.  In addition, both the demon and master will inflict 3% more damage.  Lasts as long as the demon is active.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_GatherShadows",
						["Rank"] = "0:1",
					},
					["Improved Firestone"] = {
						["Location"] = "5:4",
						["Tooltip"] = "Improved Firestone<br>Rank 0/2<br>Increases the bonus Fire damage from Firestones and the Firestone effect by 15%.",
						["Texture"] = "Interface\\Icons\\INV_Ammo_FireTar",
						["Rank"] = "0:2",
					},
					["Fel Domination"] = {
						["Location"] = "3:2",
						["Tooltip"] = "Fel Domination<br>Rank 1/1<br>Instant	15 min cooldown<br>Your next Imp, Voidwalker, Succubus, or Felhunter Summon spell has its casting time reduced by 5.5 sec and its Mana cost reduced by 50%.",
						["Texture"] = "Interface\\Icons\\Spell_Nature_RemoveCurse",
						["Rank"] = "1:1",
					},
					["Improved Enslave Demon"] = {
						["Location"] = "5:1",
						["Tooltip"] = "Improved Enslave Demon<br>Rank 0/5<br>Reduces the Attack Speed and Casting Speed penalty of your Enslave Demon spell by 2% and reduces the resist chance by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_EnslaveDemon",
						["Rank"] = "0:5",
					},
					["Unholy Power"] = {
						["Location"] = "4:3",
						["Tooltip"] = "Unholy Power<br>Rank 3/5<br>Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 12%.<br> <br>Next rank:<br>Increases the damage done by your Voidwalker, Succubus, and Felhunter's melee attacks by 16%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ShadowWordDominate",
						["Rank"] = "3:5",
					},
					["Fel Stamina"] = {
						["Location"] = "3:3",
						["Tooltip"] = "Fel Stamina<br>Rank 0/5<br>Increases the maximum Health of your Imp, Voidwalker, Succubus, and Felhunter by 3%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_AntiShadow",
						["Rank"] = "0:5",
					},
					["Demonic Embrace"] = {
						["Location"] = "1:3",
						["Tooltip"] = "Demonic Embrace<br>Rank 5/5<br>Increases your total Stamina by 15% but reduces your total Spirit by 5%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_Metamorphosis",
						["Rank"] = "5:5",
					},
				},
				["Affliction"] = {
					["Dark Pact"] = {
						["Location"] = "7:2",
						["Tooltip"] = "Dark Pact<br>Rank 0/1<br>Requires 30 points in Affliction Talents<br>20 yd range<br>Instant<br>Drains 150 of your pet's Mana, returning 100% to you.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_DarkRitual",
						["Rank"] = "0:1",
					},
					["Improved Corruption"] = {
						["Location"] = "1:3",
						["Tooltip"] = "Improved Corruption<br>Rank 5/5<br>Reduces the casting time of your Corruption spell by 2 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_AbominationExplosion",
						["Rank"] = "5:5",
					},
					["Improved Drain Soul"] = {
						["Location"] = "2:2",
						["Tooltip"] = "Improved Drain Soul<br>Rank 0/2<br>Gives you a 50% chance to get a 100% increase to your Mana regeneration for 10 sec if the target is killed by you while you drain its soul.  In addition your Mana may continue to regenerate while casting at 50% of normal.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_Haunting",
						["Rank"] = "0:2",
					},
					["Improved Curse of Weakness"] = {
						["Location"] = "2:1",
						["Tooltip"] = "Improved Curse of Weakness<br>Rank 0/3<br>Increases the effect of your Curse of Weakness by 6%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_CurseOfMannoroth",
						["Rank"] = "0:3",
					},
					["Improved Life Tap"] = {
						["Location"] = "2:3",
						["Tooltip"] = "Improved Life Tap<br>Rank 2/2<br>Increases the amount of Mana awarded by your Life Tap spell by 20%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_BurningSpirit",
						["Rank"] = "2:2",
					},
					["Suppression"] = {
						["Location"] = "1:2",
						["Tooltip"] = "Suppression<br>Rank 0/5<br>Reduces the chance for enemies to resist your Affliction spells by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_UnsummonBuilding",
						["Rank"] = "0:5",
					},
					["Background"] = "Interface\\TalentFrame\\WarlockCurses",
					["Improved Drain Life"] = {
						["Location"] = "2:4",
						["Tooltip"] = "Improved Drain Life<br>Rank 0/5<br>Increases the Health drained by your Drain Life spell by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_LifeDrain02",
						["Rank"] = "0:5",
					},
					["Amplify Curse"] = {
						["Location"] = "3:3",
						["Tooltip"] = "Amplify Curse<br>Rank 0/1<br>Requires 10 points in Affliction Talents<br>Instant	3 min cooldown<br>Increases the effect of your next Curse of Weakness or Curse of Agony by 50%, or your next Curse of Exhaustion by 20%.  Lasts 30 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_Contagion",
						["Rank"] = "0:1",
					},
					["Siphon Life"] = {
						["Location"] = "5:2",
						["Tooltip"] = "Siphon Life<br>Rank 0/1<br>Requires 20 points in Affliction Talents<br>150 Mana	30 yd range<br>Instant cast<br>Transfers 15 health from the target to the caster every 3 sec.  Lasts 30 sec.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_Requiem",
						["Rank"] = "0:1",
					},
					["Improved Drain Mana"] = {
						["Location"] = "4:4",
						["Tooltip"] = "Improved Drain Mana<br>Rank 0/2<br>Requires 15 points in Affliction Talents<br>Causes 15% of the Mana drained by your Drain Mana spell to damage the opponent.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_SiphonMana",
						["Rank"] = "0:2",
					},
					["PointsSpent"] = 7,
					["Improved Curse of Agony"] = {
						["Location"] = "3:1",
						["Tooltip"] = "Improved Curse of Agony<br>Rank 0/3<br>Requires 10 points in Affliction Talents<br>Increases the damage done by your Curse of Agony by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras",
						["Rank"] = "0:3",
					},
					["Improved Curse of Exhaustion"] = {
						["Location"] = "5:4",
						["Tooltip"] = "Improved Curse of Exhaustion<br>Rank 0/4<br>Requires 1 point in Curse of Exhaustion<br>Requires 20 points in Affliction Talents<br>Increases the speed reduction of your Curse of Exhaustion by 5%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_GrimWard",
						["Rank"] = "0:4",
					},
					["Shadow Mastery"] = {
						["Location"] = "6:2",
						["Tooltip"] = "Shadow Mastery<br>Rank 0/5<br>Requires 1 point in Siphon Life<br>Requires 25 points in Affliction Talents<br>Increases the damage dealt or life drained by your Shadow spells by 2%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_ShadeTrueSight",
						["Rank"] = "0:5",
					},
					["Curse of Exhaustion"] = {
						["Location"] = "5:3",
						["Tooltip"] = "Curse of Exhaustion<br>Rank 0/1<br>Requires 1 point in Amplify Curse<br>Requires 20 points in Affliction Talents<br>109 Mana	30 yd range<br>Instant cast<br>Reduces the target's movement speed by 10% for 12 sec.  Only one Curse per Warlock can be active on any one target.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_GrimWard",
						["Rank"] = "0:1",
					},
					["Fel Concentration"] = {
						["Location"] = "3:2",
						["Tooltip"] = "Fel Concentration<br>Rank 0/5<br>Requires 10 points in Affliction Talents<br>Gives you a 14% chance to avoid interruption caused by damage while channeling the Drain Life, Drain Mana, or Drain Soul spell.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_FingerOfDeath",
						["Rank"] = "0:5",
					},
					["Order"] = 1,
					["Grim Reach"] = {
						["Location"] = "4:1",
						["Tooltip"] = "Grim Reach<br>Rank 0/2<br>Requires 15 points in Affliction Talents<br>Increases the range of your Affliction spells by 10%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_CallofBone",
						["Rank"] = "0:2",
					},
					["Nightfall"] = {
						["Location"] = "4:2",
						["Tooltip"] = "Nightfall<br>Rank 0/2<br>Requires 15 points in Affliction Talents<br>Gives your Corruption and Drain Life spells a 2% chance to cause you to enter a Shadow Trance state after damaging the opponent.  The Shadow Trance state reduces the casting time of your next Shadow Bolt spell by 100%.",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_Twilight",
						["Rank"] = "0:2",
					},
				},
			},
			["ClassEn"] = "WARLOCK",
			["Zone"] = "Un'Goro Crater",
			["Date"] = "12/25/19 00:54:59",
			["SexId"] = 0,
			["Server"] = "Kronos",
			["TimePlayed"] = 1393083,
			["Pets"] = {
				["Graz'vhug"] = {
					["Stats"] = {
						["Intellect"] = "70:70:0:0",
						["Defense"] = "300:300:0:0",
						["Strength"] = "129:129:0:0",
						["Agility"] = "85:85:0:0",
						["Armor"] = "4745:4745:0:0",
						["Spirit"] = "150:150:0:0",
						["Stamina"] = "249:249:0:0",
					},
					["Melee Attack"] = {
						["AttackPower"] = 238,
						["AttackSpeed"] = "2.00",
						["AttackDPS"] = "59.1",
						["DamageRangeBase"] = "101:135",
						["AttackPower2"] = "238:238:0:0",
						["AttackRating"] = 300,
						["DamageRange"] = "101:135",
						["DamageRangeTooltip"] = "Main Hand<br>Attack Speed (seconds):	2.00<br>Damage:	101 - 135<br>Damage per Second:	59.1",
						["AttackPowerDPS"] = "17.0",
						["AttackPowerTooltip"] = "Increases damage with melee weapons by 17.0 damage per second.",
					},
					["Mana"] = 1930,
					["TalentPointsUsed"] = 0,
					["Resists"] = {
						["Shadow"] = "0:0:0:0",
						["Arcane"] = "0:0:0:0",
						["Holy"] = "0:0:0:0",
						["Fire"] = "0:0:0:0",
						["Frost"] = "0:0:0:0",
						["Nature"] = "0:0:0:0",
					},
					["Armor"] = "4745:4745:0",
					["Level"] = 60,
					["Type"] = "Voidwalker",
					["TalentPoints"] = 0,
					["Power"] = "Mana",
					["Experience"] = "0:0",
					["SpellBook"] = {
						["Spells"] = {
							["Consume Shadows"] = {
								["Rank"] = "Rank 6",
								["Texture"] = "Interface\\Icons\\Spell_Shadow_AntiShadow",
							},
							["Sacrifice"] = {
								["Rank"] = "Rank 6",
								["Texture"] = "Interface\\Icons\\Spell_Shadow_SacrificialShield",
							},
							["Torment"] = {
								["Rank"] = "Rank 6",
								["Texture"] = "Interface\\Icons\\Spell_Shadow_GatherShadows",
							},
							["Suffering"] = {
								["Rank"] = "Rank 4",
								["Texture"] = "Interface\\Icons\\Spell_Shadow_BlackPlague",
							},
						},
						["Count"] = 4,
					},
					["Health"] = 3419,
					["Name"] = "Graz'vhug",
					["Defense"] = 300,
				},
			},
			["DBversion"] = "1.6.2",
			["Hearth"] = "Gadgetzan",
			["Resists"] = {
				["Holy"] = "0:0:0:0",
				["Arcane"] = "0:10:10:0",
				["Shadow"] = "0:0:0:0",
				["Fire"] = "7:7:0:0",
				["Frost"] = "0:0:0:0",
				["Nature"] = "0:0:0:0",
			},
			["Armor"] = "700:700:0",
			["Level"] = 60,
			["XP"] = "224:0:0",
			["Bank"] = {
				["Contents"] = {
					[1] = {
						["Quantity"] = 1,
						["Name"] = "Ward of the Elements",
						["Color"] = "ff1eff00",
						["Tooltip"] = "Ward of the Elements<br>Soulbound<br>Trinket<br>+8 Arcane Resistance<br>+8 Fire Resistance<br>+8 Nature Resistance<br>+8 Frost Resistance<br>+8 Shadow Resistance",
						["Item"] = "12065:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Jewelry_Talisman_02",
					},
					[2] = {
						["Quantity"] = 1,
						["Name"] = "Serpentine Skuller",
						["Color"] = "ff0070dd",
						["Tooltip"] = "Serpentine Skuller<br>Soulbound<br>Wand<br>53 - 100 Shadow Damage	Speed 1.40<br>(54.6 damage per second)<br>+10 Shadow Resistance<br>Durability 65 / 65<br>Requires Level 51",
						["Item"] = "12605:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Misc_Bone_ElfSkull_01",
					},
					[3] = {
						["Quantity"] = 1,
						["Name"] = "Evergreen Pouch",
						["Color"] = "ffffffff",
						["Tooltip"] = "Evergreen Pouch<br>Soulbound<br>Unique<br>Use: Consume two Un'Goro Soil samples and a Packet of Tharlendris seeds to make an Evergreen Herb Casing.",
						["Item"] = "11020:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Misc_Bag_18",
					},
					[4] = {
						["Quantity"] = 28,
						["Name"] = "Stratholme Holy Water",
						["Color"] = "ffffffff",
						["Tooltip"] = "Stratholme Holy Water<br>Soulbound<br>Use: Inflicts between 438 and 562 damage to Undead in a 10 yard radius.<br>\"Just 1 calorie.\"",
						["Item"] = "13180:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Potion_75",
					},
					[5] = {
						["Quantity"] = 1,
						["Name"] = "Winterfall Spirit Beads",
						["Color"] = "ffffffff",
						["Tooltip"] = "Winterfall Spirit Beads<br>Soulbound<br>\"These may be gathered for the Timbermaw furbolgs to earn their trust.\"",
						["Item"] = "21383:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Jewelry_Amulet_05",
					},
					[6] = {
						["Quantity"] = 2,
						["Name"] = "Insignia of the Crusade",
						["Color"] = "ff1eff00",
						["Tooltip"] = "Insignia of the Crusade<br>Soulbound",
						["Item"] = "22524:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Misc_Token_ScarletCrusade",
					},
					[7] = {
						["Quantity"] = 1,
						["Name"] = "Soul Harvester",
						["Color"] = "ff0070dd",
						["Tooltip"] = "Soul Harvester<br>Soulbound<br>Two-Hand	Staff<br>118 - 178 Damage	Speed 3.30<br>(44.8 damage per second)<br>+16 Stamina<br>Durability 90 / 100<br>Equip: Improves your chance to hit with spells by 1%.<br>Equip: Increases damage done by Shadow spells and effects by up to 24.",
						["Item"] = "20536:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Sword_48",
					},
					[8] = {
						["Quantity"] = 1,
						["Name"] = "Zanzil's Band",
						["Color"] = "ff0070dd",
						["Tooltip"] = "Zanzil's Band<br>Soulbound<br>Unique<br>Finger<br>+13 Intellect<br>Requires Level 60<br>Equip: Improves your chance to hit with spells by 1%.<br>Equip: Restores 4 mana per 5 sec.<br> <br><br>Zanzil's Concentration (0/2)<br>  Zanzil's Band<br>  Zanzil's Seal<br> <br><br>(2) Set: Improves your chance to hit with spells by 1%.<br>(2) Set: Increases damage and healing done by magical spells and effects by up to 6.",
						["Item"] = "19905:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Jewelry_Ring_46",
					},
					[9] = {
						["Quantity"] = 1,
						["Name"] = "Tearfall Bracers of Fiery Wrath",
						["Color"] = "ff0070dd",
						["Tooltip"] = "Tearfall Bracers of Fiery Wrath<br>Soulbound<br>Wrist	Cloth<br>35 Armor<br>+21 Fire Spell Damage<br>Durability 30 / 30<br>Requires Level 52",
						["Item"] = "13409:0:1889:0",
						["Texture"] = "Interface\\Icons\\INV_Bracer_13",
					},
					[10] = {
						["Quantity"] = 1,
						["Name"] = "Barov Peasant Caller",
						["Color"] = "ff0070dd",
						["Tooltip"] = "Barov Peasant Caller<br>Soulbound<br>Trinket<br>Use: Calls forth 3 servants of the House Barov that will fight, cook, and clean for you.",
						["Item"] = "14023:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Misc_Bell_01",
					},
					[11] = {
						["Quantity"] = 16,
						["Name"] = "Deadwood Headdress Feather",
						["Color"] = "ffffffff",
						["Tooltip"] = "Deadwood Headdress Feather<br>Soulbound<br>\"These may be gathered for the Timbermaw furbolgs to earn their trust.\"",
						["Item"] = "21377:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Feather_13",
					},
					[12] = {
						["Quantity"] = 2,
						["Name"] = "Insignia of the Dawn",
						["Color"] = "ff1eff00",
						["Tooltip"] = "Insignia of the Dawn<br>Soulbound",
						["Item"] = "22523:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Misc_Token_ArgentDawn",
					},
					[13] = {
						["Quantity"] = 1,
						["Name"] = "Primal Hakkari Sash",
						["Color"] = "ffa335ee",
						["Tooltip"] = "Primal Hakkari Sash<br>Soulbound<br>Classes: Priest, Warlock, Druid<br>\"A legendary Paragon of Power from the old Gurubashi Empire.\"",
						["Item"] = "19720:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Belt_07",
					},
					[14] = {
						["Quantity"] = 1,
						["Name"] = "Primal Hakkari Kossack",
						["Color"] = "ffa335ee",
						["Tooltip"] = "Primal Hakkari Kossack<br>Soulbound<br>Classes: Warrior, Mage, Warlock<br>\"A legendary Paragon of Power from the old Gurubashi Empire.\"",
						["Item"] = "19723:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Shirt_07",
					},
					[17] = {
						["Quantity"] = 1,
						["Name"] = "Deadwood Ritual Totem",
						["Color"] = "ffffffff",
						["Tooltip"] = "Deadwood Ritual Totem<br>Soulbound<br>Unique<br>This Item Begins a Quest<br>Requires Level 45<br>\"The totem is thick with the taint of corruption.\"",
						["Item"] = "20741:0:0:0",
						["Texture"] = "Interface\\Icons\\Spell_Totem_WardOfDraining",
					},
					[18] = {
						["Quantity"] = 1,
						["Name"] = "Sprite Darter Egg",
						["Color"] = "ffffffff",
						["Tooltip"] = "Sprite Darter Egg<br>Soulbound<br>Use: Right Click to summon and dismiss your sprite darter hatchling.",
						["Item"] = "11474:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Egg_02",
					},
					[19] = {
						["Quantity"] = 1,
						["Name"] = "Qiraji Ornate Hilt",
						["Color"] = "ffa335ee",
						["Tooltip"] = "Qiraji Ornate Hilt<br>Soulbound<br>Classes: Priest, Mage, Warlock, Druid",
						["Item"] = "20890:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Qiraj_HiltOrnate",
					},
					[20] = {
						["Quantity"] = 1,
						["Name"] = "Qiraji Regal Drape",
						["Color"] = "ff0070dd",
						["Tooltip"] = "Qiraji Regal Drape<br>Soulbound<br>Classes: Paladin, Hunter, Shaman, Warlock, Druid",
						["Item"] = "20889:0:0:0",
						["Texture"] = "Interface\\Icons\\INV_Bracer_18",
					},
					[23] = {
						["Quantity"] = 1,
						["Name"] = "Winterfall Ritual Totem",
						["Color"] = "ffffffff",
						["Tooltip"] = "Winterfall Ritual Totem<br>Soulbound<br>Unique<br>This Item Begins a Quest<br>Requires Level 50<br>\"The totem is thick with the taint of corruption.\"",
						["Item"] = "20742:0:0:0",
						["Texture"] = "Interface\\Icons\\Spell_Fire_FrostResistanceTotem",
					},
					[24] = {
						["Quantity"] = 1,
						["Name"] = "Mechanical Chicken",
						["Color"] = "ffffffff",
						["Tooltip"] = "Mechanical Chicken<br>Binds when used<br>Use: Right Click to summon and dismiss your chicken.",
						["Item"] = "10398:0:0:0",
						["Texture"] = "Interface\\Icons\\Spell_Magic_PolymorphChicken",
					},
				},
				["Bag1"] = {
					["Contents"] = {
						[1] = {
							["Quantity"] = 1,
							["Name"] = "Drakefire Amulet",
							["Color"] = "ff0070dd",
							["Tooltip"] = "Drakefire Amulet<br>Soulbound<br>Unique<br>Neck<br>+10 Stamina<br>+15 Fire Resistance<br>Requires Level 50<br>\"The Blood of Drakkisath Flows Within...\"",
							["Item"] = "16309:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Jewelry_Talisman_11",
						},
						[2] = {
							["Quantity"] = 1,
							["Name"] = "Spectral Essence",
							["Color"] = "ff1eff00",
							["Tooltip"] = "Spectral Essence<br>Soulbound<br>Unique<br>Trinket<br>\"Allows communication with the deceased of Caer Darrow.\"",
							["Item"] = "13544:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Orb_05",
						},
						[14] = {
							["Quantity"] = 1,
							["Name"] = "Scepter of Celebras",
							["Color"] = "ff0070dd",
							["Tooltip"] = "Scepter of Celebras<br>Soulbound<br>Unique<br>Use: Creates a portal, teleporting group members that use it to Earth Song Falls in inner Maraudon.",
							["Item"] = "17191:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Staff_16",
						},
					},
					["Color"] = "ffffffff",
					["Tooltip"] = "Journeyman's Backpack<br>14 Slot Bag",
					["Slots"] = 14,
					["Name"] = "Journeyman's Backpack",
					["Item"] = "3914:0:0:0",
					["Texture"] = "Interface\\Icons\\INV_Misc_Bag_07_Black",
				},
			},
			["TimeLevelPlayed"] = 824197,
			["Defense"] = 300,
			["TalentPoints"] = 0,
			["Honor"] = {
				["LifetimeHK"] = 39,
				["LastWeek"] = {
					["HK"] = 2,
					["Contribution"] = 340,
					["Rank"] = 0,
					["DK"] = 0,
				},
				["LifetimeHighestRank"] = 0,
				["RankInfo"] = "(Rank 0)",
				["ThisWeek"] = {
					["Contribution"] = 0,
					["HK"] = 0,
				},
				["Yesterday"] = {
					["HK"] = 0,
					["Contribution"] = 0,
					["DK"] = 0,
				},
				["YesterdayContribution"] = 0,
				["YesterdayHK"] = 0,
				["LifetimeDK"] = 0,
				["RankName"] = "None",
				["SessionDK"] = 0,
				["SessionHK"] = 0,
				["LastWeekRank"] = 0,
				["YesterdayDK"] = 0,
				["LifetimeRankName"] = "None",
				["LastWeekContribution"] = 340,
				["Current"] = {
					["Description"] = "(Rank 0)",
					["Progress"] = "0.00",
					["Icon"] = "",
					["Rank"] = "None",
				},
				["Lifetime"] = {
					["Name"] = "None",
					["HK"] = 39,
					["DK"] = 0,
					["Rank"] = 0,
				},
				["LastWeekHK"] = 2,
				["RankIcon"] = "",
				["Session"] = {
					["DK"] = 0,
					["HK"] = 0,
				},
				["LastWeekDK"] = 0,
			},
			["Money"] = {
				["Silver"] = 91,
				["Gold"] = 106,
				["Copper"] = 37,
			},
			["ParryPercent"] = "0",
			["ProfilerVersion"] = "1.6.2",
			["IsResting"] = false,
			["CPprovider"] = "rpgo",
			["DateUpdated"] = "12/25/19 00:54:59",
			["Name"] = "Malyg",
			["Sex"] = "Male",
			["DodgePercent"] = "4.65",
			["Skills"] = {
				["Secondary Skills"] = {
					["Fishing"] = "300:300",
					["Order"] = 3,
					["First Aid"] = "300:300",
					["Riding"] = "150:150",
				},
				["Class Skills"] = {
					["Destruction"] = "1:1",
					["Order"] = 1,
					["Demonology"] = "1:1",
				},
				["Professions"] = {
					["Skinning"] = "300:300",
					["Order"] = 2,
					["Herbalism"] = "300:300",
				},
				["Languages"] = {
					["Order"] = 6,
					["Language: Gnomish"] = "300:300",
					["Language: Common"] = "300:300",
				},
				["Armor Proficiencies"] = {
					["Cloth"] = "1:1",
					["Order"] = 5,
				},
				["Weapon Skills"] = {
					["Defense"] = "300:300",
					["Order"] = 4,
					["Daggers"] = "81:300",
					["Staves"] = "167:300",
					["Unarmed"] = "1:300",
					["Wands"] = "300:300",
					["Swords"] = "42:300",
				},
			},
			["ServerTime"] = "00:54",
			["Power"] = "Mana",
		},
	},
	["Public Test Realm"] = {
		["Alsonait"] = {
			["Melee Attack"] = {
				["AttackPower"] = 400,
				["AttackSpeed"] = "1.90",
				["AttackDPS"] = "29.5",
				["DamageRangeBase"] = "55:57",
				["AttackPower2"] = "400:400:0:0",
				["AttackRating"] = 305,
				["DamageRange"] = "55:57",
				["DamageRangeTooltip"] = "Main Hand<br>Attack Speed (seconds):	1.90<br>Damage:	55 - 57<br>Damage per Second:	29.5",
				["AttackPowerDPS"] = "28.6",
				["AttackPowerTooltip"] = "Increases damage with melee weapons by 28.6 damage per second.",
			},
			["Mana"] = 100,
			["Locale"] = "enUS",
			["CPprovider"] = "rpgo",
			["CritPercent"] = "4.00",
			["MitigationPercent"] = "2.95",
			["Reputation"] = {
				["Alliance"] = {
					["Stormwind"] = {
						["Standing"] = "Friendly",
						["Value"] = "1000/6000",
						["AtWar"] = 0,
					},
					["Ironforge"] = {
						["Standing"] = "Friendly",
						["Value"] = "100/6000",
						["AtWar"] = 0,
					},
					["Darnassus"] = {
						["Standing"] = "Friendly",
						["Value"] = "100/6000",
						["AtWar"] = 0,
					},
					["Gnomeregan Exiles"] = {
						["Standing"] = "Friendly",
						["Value"] = "100/6000",
						["AtWar"] = 0,
					},
				},
				["Count"] = 5,
			},
			["timestamp"] = {
				["Equipment"] = 1575135638,
				["Stats"] = 1575137817,
				["init"] = {
					["TimeStamp"] = 1575137817,
					["Date"] = "11/30/19 19:16:57",
					["ServerTime"] = "19:16",
					["DateUTC"] = "11/30/19 18:16:57",
				},
				["Inventory"] = 1575137817,
			},
			["FactionEn"] = "Alliance",
			["Power"] = "Rage",
			["Equipment"] = {
				["Shirt"] = {
					["Item"] = "38:0:0:0",
					["Color"] = "ffffffff",
					["Tooltip"] = "Recruit's Shirt<br>Shirt",
					["Name"] = "Recruit's Shirt",
					["Texture"] = "Interface\\Icons\\INV_Shirt_05",
				},
				["Legs"] = {
					["Item"] = "39:0:0:0",
					["Color"] = "ff9d9d9d",
					["Tooltip"] = "Recruit's Pants<br>Legs	Cloth<br>2 Armor<br>Durability 25 / 25",
					["Name"] = "Recruit's Pants",
					["Texture"] = "Interface\\Icons\\INV_Pants_02",
				},
				["MainHand"] = {
					["Item"] = "25:0:0:0",
					["Color"] = "ffffffff",
					["Tooltip"] = "Worn Shortsword<br>Main Hand	Sword<br>1 - 3 Damage	Speed 1.90<br>(1.1 damage per second)<br>Durability 20 / 20",
					["Name"] = "Worn Shortsword",
					["Texture"] = "Interface\\Icons\\INV_Sword_04",
				},
				["SecondaryHand"] = {
					["Item"] = "2362:0:0:0",
					["Color"] = "ff9d9d9d",
					["Tooltip"] = "Worn Wooden Shield<br>Off Hand	Shield<br>5 Armor<br>1 Block<br>Durability 20 / 20",
					["Name"] = "Worn Wooden Shield",
					["Texture"] = "Interface\\Icons\\INV_Shield_09",
				},
				["Feet"] = {
					["Item"] = "40:0:0:0",
					["Color"] = "ffffffff",
					["Tooltip"] = "Recruit's Boots<br>Feet",
					["Name"] = "Recruit's Boots",
					["Texture"] = "Interface\\Icons\\INV_Boots_06",
				},
			},
			["DateUTC"] = "11/30/19 18:16:57",
			["Health"] = 2609,
			["CPversion"] = "1.6.3",
			["BlockPercent"] = "5.00",
			["RaceEn"] = "Human",
			["DateUpdated"] = "11/30/19 19:16:57",
			["IsResting"] = false,
			["ParryPercent"] = "0",
			["Stats"] = {
				["Intellect"] = "30:30:0:0",
				["Defense"] = "300:300:0:0",
				["Strength"] = "120:120:0:0",
				["Agility"] = "80:80:0:0",
				["Armor"] = "167:167:0:0",
				["Spirit"] = "49:49:0:0",
				["Stamina"] = "110:110:0:0",
			},
			["ClassEn"] = "WARRIOR",
			["Zone"] = "Dustwallow Marsh",
			["Date"] = "11/30/19 19:16:57",
			["SexId"] = 1,
			["Name"] = "Alsonait",
			["SubZone"] = "Theramore Isle",
			["Class"] = "Warrior",
			["TimePlayed"] = 2196,
			["Race"] = "Human",
			["Resists"] = {
				["Shadow"] = "0:0:0:0",
				["Arcane"] = "0:0:0:0",
				["Holy"] = "0:0:0:0",
				["Fire"] = "0:0:0:0",
				["Frost"] = "0:0:0:0",
				["Nature"] = "0:0:0:0",
			},
			["Armor"] = "167:167:0",
			["Level"] = 60,
			["XP"] = "0:0:0",
			["Hearth"] = "Elwynn Forest",
			["HasRelicSlot"] = false,
			["Defense"] = 300,
			["TalentPoints"] = 51,
			["DBversion"] = "1.6.2",
			["Money"] = {
				["Silver"] = 0,
				["Gold"] = 0,
				["Copper"] = 0,
			},
			["TimeLevelPlayed"] = 2179,
			["ProfilerVersion"] = "1.6.2",
			["Server"] = "Public Test Realm",
			["Inventory"] = {
				["Bag0"] = {
					["Contents"] = {
						[1] = {
							["Quantity"] = 5,
							["Name"] = "Tough Jerky",
							["Color"] = "ffffffff",
							["Tooltip"] = "Tough Jerky<br>Use: Restores 61 health over 18 sec.  Must remain seated while eating.",
							["Item"] = "117:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Food_16",
						},
						[2] = {
							["Quantity"] = 1,
							["Name"] = "Hearthstone",
							["Color"] = "ffffffff",
							["Tooltip"] = "Hearthstone<br>Soulbound<br>Unique<br>Use: Returns you to Elwynn Forest.  Speak to an Innkeeper in a different place to change your home location.",
							["Item"] = "6948:0:0:0",
							["Texture"] = "Interface\\Icons\\INV_Misc_Rune_01",
						},
					},
					["Color"] = "ffffffff",
					["Tooltip"] = "Backpack<br>16 Slot ",
					["Slots"] = 16,
					["Name"] = "Backpack",
					["Item"] = "0:0:0:0",
					["Texture"] = "Interface\\Buttons\\Button-Backpack-Up",
				},
			},
			["Talents"] = {
				["Protection"] = {
					["Shield Slam"] = {
						["Location"] = "7:2",
						["Tooltip"] = "Shield Slam<br>Rank 0/1<br>Requires 1 point in Concussion Blow<br>Requires 30 points in Protection Talents<br>20 Rage	5 yd range<br>Instant	6 sec cooldown<br>Requires Shields<br>Slam the target with your shield, causing 225 to 235 damage, modified by your shield block value, and has a 50% chance of dispelling 1 magic effect on the target.  Also causes a high amount of threat.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\INV_Shield_05",
					},
					["Concussion Blow"] = {
						["Location"] = "5:2",
						["Tooltip"] = "Concussion Blow<br>Rank 0/1<br>Requires 20 points in Protection Talents<br>15 Rage	5 yd range<br>Instant	45 sec cooldown<br>Requires Melee Weapon<br>Stuns the opponent for 5 sec.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Ability_ThunderBolt",
					},
					["Order"] = 3,
					["Defiance"] = {
						["Location"] = "3:4",
						["Tooltip"] = "Defiance<br>Rank 0/5<br>Requires 10 points in Protection Talents<br>Increases the threat generated by your attacks by 3% while in Defensive Stance.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_InnerRage",
					},
					["Improved Disarm"] = {
						["Location"] = "4:2",
						["Tooltip"] = "Improved Disarm<br>Rank 0/3<br>Requires 15 points in Protection Talents<br>Increases the duration of your Disarm ability by 1 secs.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_Disarm",
					},
					["Background"] = "Interface\\TalentFrame\\WarriorProtection",
					["Improved Revenge"] = {
						["Location"] = "3:3",
						["Tooltip"] = "Improved Revenge<br>Rank 0/3<br>Requires 10 points in Protection Talents<br>Gives your Revenge ability a 15% chance to stun the target for 3 sec.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_Revenge",
					},
					["Improved Bloodrage"] = {
						["Location"] = "2:1",
						["Tooltip"] = "Improved Bloodrage<br>Rank 0/2<br>Requires 5 points in Protection Talents<br>Increases the instant Rage generated by your Bloodrage ability by 2.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Ability_Racial_BloodRage",
					},
					["Toughness"] = {
						["Location"] = "2:3",
						["Tooltip"] = "Toughness<br>Rank 0/5<br>Requires 5 points in Protection Talents<br>Increases your armor value from items by 2%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Holy_Devotion",
					},
					["Improved Sunder Armor"] = {
						["Location"] = "4:1",
						["Tooltip"] = "Improved Sunder Armor<br>Rank 0/3<br>Requires 15 points in Protection Talents<br>Reduces the cost of your Sunder Armor ability by 1 rage point.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_Sunder",
					},
					["Iron Will"] = {
						["Location"] = "2:4",
						["Tooltip"] = "Iron Will<br>Rank 0/5<br>Requires 5 points in Protection Talents<br>Increases your chance to resist Stun and Charm effects by an additional 3%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Magic_MageArmor",
					},
					["Shield Specialization"] = {
						["Location"] = "1:2",
						["Tooltip"] = "Shield Specialization<br>Rank 0/5<br>Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs.<br>Click to learn",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Shield_06",
					},
					["Improved Shield Wall"] = {
						["Location"] = "5:1",
						["Tooltip"] = "Improved Shield Wall<br>Rank 0/2<br>Requires 20 points in Protection Talents<br>Increases the effect duration of your Shield Wall ability by 3 secs.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_ShieldWall",
					},
					["PointsSpent"] = 0,
					["Improved Shield Bash"] = {
						["Location"] = "5:3",
						["Tooltip"] = "Improved Shield Bash<br>Rank 0/2<br>Requires 20 points in Protection Talents<br>Gives your Shield Bash ability a 50% chance to silence the target for 3 sec.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_ShieldBash",
					},
					["Anticipation"] = {
						["Location"] = "1:3",
						["Tooltip"] = "Anticipation<br>Rank 0/5<br>Increases your Defense skill by 2.<br>Click to learn",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Nature_MirrorImage",
					},
					["Improved Shield Block"] = {
						["Location"] = "3:2",
						["Tooltip"] = "Improved Shield Block<br>Rank 0/3<br>Requires 5 points in Shield Specialization<br>Requires 10 points in Protection Talents<br>Allows your Shield Block ability to block an additional attack and increases the duration by 0.5 second.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Defend",
					},
					["Improved Taunt"] = {
						["Location"] = "4:3",
						["Tooltip"] = "Improved Taunt<br>Rank 0/2<br>Requires 15 points in Protection Talents<br>Reduces the cooldown of your Taunt ability by 1 sec.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Spell_Nature_Reincarnation",
					},
					["One-Handed Weapon Specialization"] = {
						["Location"] = "6:3",
						["Tooltip"] = "One-Handed Weapon Specialization<br>Rank 0/5<br>Requires 25 points in Protection Talents<br>Increases the damage you deal with One-Handed Melee weapons by 2%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Sword_20",
					},
					["Last Stand"] = {
						["Location"] = "3:1",
						["Tooltip"] = "Last Stand<br>Rank 0/1<br>Requires 2 points in Improved Bloodrage<br>Requires 10 points in Protection Talents<br>Instant	10 min cooldown<br>When activated, this ability temporarily grants you 30% of your maximum hit points for 20 seconds.  After the effect expires, the hit points are lost.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Spell_Holy_AshesToAshes",
					},
				},
				["Fury"] = {
					["Improved Berserker Rage"] = {
						["Location"] = "6:1",
						["Tooltip"] = "Improved Berserker Rage<br>Rank 0/2<br>Requires 25 points in Fury Talents<br>The Berserker Rage ability will generate 5 rage when used.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Spell_Nature_AncestralGuardian",
					},
					["Improved Execute"] = {
						["Location"] = "4:2",
						["Tooltip"] = "Improved Execute<br>Rank 0/2<br>Requires 15 points in Fury Talents<br>Reduces the Rage cost of your Execute ability by 2.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\INV_Sword_48",
					},
					["Improved Demoralizing Shout"] = {
						["Location"] = "2:2",
						["Tooltip"] = "Improved Demoralizing Shout<br>Rank 0/5<br>Requires 5 points in Fury Talents<br>Increases the melee attack power reduction of your Demoralizing Shout by 8%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_WarCry",
					},
					["Blood Craze"] = {
						["Location"] = "3:3",
						["Tooltip"] = "Blood Craze<br>Rank 0/3<br>Requires 10 points in Fury Talents<br>Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_SummonImp",
					},
					["Improved Intercept"] = {
						["Location"] = "5:4",
						["Tooltip"] = "Improved Intercept<br>Rank 0/2<br>Requires 20 points in Fury Talents<br>Reduces the cooldown of your Intercept ability by 5 sec.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Ability_Rogue_Sprint",
					},
					["Unbridled Wrath"] = {
						["Location"] = "2:3",
						["Tooltip"] = "Unbridled Wrath<br>Rank 0/5<br>Requires 5 points in Fury Talents<br>Gives you a 8% chance to generate an additional Rage point when you deal melee damage with a weapon.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Nature_StoneClawTotem",
					},
					["Bloodthirst"] = {
						["Location"] = "7:2",
						["Tooltip"] = "Bloodthirst<br>Rank 0/1<br>Requires 1 point in Death Wish<br>Requires 30 points in Fury Talents<br>30 Rage	5 yd range<br>Instant	6 sec cooldown<br>Instantly attack the target causing damage equal to 45% of your attack power.  In addition, the next 5 successful melee attacks will restore 10 health.  This effect lasts 8 sec.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Spell_Nature_BloodLust",
					},
					["Improved Slam"] = {
						["Location"] = "5:1",
						["Tooltip"] = "Improved Slam<br>Rank 0/5<br>Requires 20 points in Fury Talents<br>Decreases the casting time of your Slam ability by 0.1 sec.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_DecisiveStrike",
					},
					["Flurry"] = {
						["Location"] = "6:3",
						["Tooltip"] = "Flurry<br>Rank 0/5<br>Requires 5 points in Enrage<br>Requires 25 points in Fury Talents<br>Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_GhoulFrenzy",
					},
					["Background"] = "Interface\\TalentFrame\\WarriorFury",
					["Booming Voice"] = {
						["Location"] = "1:2",
						["Tooltip"] = "Booming Voice<br>Rank 0/5<br>Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%.<br>Click to learn",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Nature_Purge",
					},
					["Cruelty"] = {
						["Location"] = "1:3",
						["Tooltip"] = "Cruelty<br>Rank 0/5<br>Increases your chance to get a critical strike with melee weapons by 1%.<br>Click to learn",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_Rogue_Eviscerate",
					},
					["PointsSpent"] = 0,
					["Improved Cleave"] = {
						["Location"] = "3:1",
						["Tooltip"] = "Improved Cleave<br>Rank 0/3<br>Requires 10 points in Fury Talents<br>Increases the bonus damage done by your Cleave ability by 40%.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_Cleave",
					},
					["Dual Wield Specialization"] = {
						["Location"] = "4:1",
						["Tooltip"] = "Dual Wield Specialization<br>Rank 0/5<br>Requires 15 points in Fury Talents<br>Increases the damage done by your offhand weapon by 5%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_DualWield",
					},
					["Piercing Howl"] = {
						["Location"] = "3:2",
						["Tooltip"] = "Piercing Howl<br>Rank 0/1<br>Requires 10 points in Fury Talents<br>10 Rage<br>Instant<br>Causes all enemies near the warrior to be dazed, reducing movement speed by 50% for 6 sec.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_DeathScream",
					},
					["Order"] = 2,
					["Enrage"] = {
						["Location"] = "4:3",
						["Tooltip"] = "Enrage<br>Rank 0/5<br>Requires 15 points in Fury Talents<br>Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_UnholyFrenzy",
					},
					["Death Wish"] = {
						["Location"] = "5:2",
						["Tooltip"] = "Death Wish<br>Rank 0/1<br>Requires 20 points in Fury Talents<br>10 Rage<br>Instant	3 min cooldown<br>When activated, increases your physical damage by 20% and makes you immune to Fear effects, but lowers your armor and all resistances by 20%.  Lasts 30 sec.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Spell_Shadow_DeathPact",
					},
					["Improved Battle Shout"] = {
						["Location"] = "3:4",
						["Tooltip"] = "Improved Battle Shout<br>Rank 0/5<br>Requires 10 points in Fury Talents<br>Increases the melee attack power bonus of your Battle Shout by 5%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_BattleShout",
					},
				},
				["Arms"] = {
					["Improved Thunder Clap"] = {
						["Location"] = "2:4",
						["Tooltip"] = "Improved Thunder Clap<br>Rank 0/3<br>Requires 5 points in Arms Talents<br>Reduces the cost of your Thunder Clap ability by 1 rage point.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_ThunderClap",
					},
					["Sweeping Strikes"] = {
						["Location"] = "5:2",
						["Tooltip"] = "Sweeping Strikes<br>Rank 0/1<br>Requires 20 points in Arms Talents<br>30 Rage<br>Instant	30 sec cooldown<br>Requires Battle Stance<br>Your next 5 melee attacks strike an additional nearby opponent.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Ability_Rogue_SliceDice",
					},
					["Improved Hamstring"] = {
						["Location"] = "6:3",
						["Tooltip"] = "Improved Hamstring<br>Rank 0/3<br>Requires 25 points in Arms Talents<br>Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_ShockWave",
					},
					["Impale"] = {
						["Location"] = "4:3",
						["Tooltip"] = "Impale<br>Rank 0/2<br>Requires 3 points in Deep Wounds<br>Requires 15 points in Arms Talents<br>Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Ability_SearingArrow",
					},
					["Background"] = "Interface\\TalentFrame\\WarriorArms",
					["Improved Heroic Strike"] = {
						["Location"] = "1:1",
						["Tooltip"] = "Improved Heroic Strike<br>Rank 0/3<br>Reduces the cost of your Heroic Strike ability by 1 rage point.<br>Click to learn",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Rogue_Ambush",
					},
					["Axe Specialization"] = {
						["Location"] = "5:1",
						["Tooltip"] = "Axe Specialization<br>Rank 0/5<br>Requires 20 points in Arms Talents<br>Increases your chance to get a critical strike with Axes by 1%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Axe_06",
					},
					["Deflection"] = {
						["Location"] = "1:2",
						["Tooltip"] = "Deflection<br>Rank 0/5<br>Increases your Parry chance by 1%.<br>Click to learn",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Ability_Parry",
					},
					["Anger Management"] = {
						["Location"] = "3:2",
						["Tooltip"] = "Anger Management<br>Rank 0/1<br>Requires 5 points in Tactical Mastery<br>Requires 10 points in Arms Talents<br>Increases the time required for your rage to decay while out of combat by 30%.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Spell_Holy_BlessingOfStamina",
					},
					["Mace Specialization"] = {
						["Location"] = "5:3",
						["Tooltip"] = "Mace Specialization<br>Rank 0/5<br>Requires 20 points in Arms Talents<br>Gives you a 1% chance to stun your target for 3 sec with a Mace.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Mace_01",
					},
					["Order"] = 1,
					["Tactical Mastery"] = {
						["Location"] = "2:2",
						["Tooltip"] = "Tactical Mastery<br>Rank 0/5<br>Requires 5 points in Arms Talents<br>You retain up to 5 of your rage points when you change stances.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\Spell_Nature_EnchantArmor",
					},
					["PointsSpent"] = 0,
					["Improved Rend"] = {
						["Location"] = "1:3",
						["Tooltip"] = "Improved Rend<br>Rank 0/3<br>Increases the bleed damage done by your Rend ability by 15%.<br>Click to learn",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_Gouge",
					},
					["Two-Handed Weapon Specialization"] = {
						["Location"] = "4:2",
						["Tooltip"] = "Two-Handed Weapon Specialization<br>Rank 0/5<br>Requires 15 points in Arms Talents<br>Increases the damage you deal with two-handed melee weapons by 1%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Axe_09",
					},
					["Improved Overpower"] = {
						["Location"] = "3:1",
						["Tooltip"] = "Improved Overpower<br>Rank 0/2<br>Requires 10 points in Arms Talents<br>Increases the critical strike chance of your Overpower ability by 25%.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\INV_Sword_05",
					},
					["Deep Wounds"] = {
						["Location"] = "3:3",
						["Tooltip"] = "Deep Wounds<br>Rank 0/3<br>Requires 3 points in Improved Rend<br>Requires 10 points in Arms Talents<br>Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapon's average damage over 12 sec.",
						["Rank"] = "0:3",
						["Texture"] = "Interface\\Icons\\Ability_BackStab",
					},
					["Polearm Specialization"] = {
						["Location"] = "6:1",
						["Tooltip"] = "Polearm Specialization<br>Rank 0/5<br>Requires 25 points in Arms Talents<br>Increases your chance to get a critical strike with Polearms by 1%.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Weapon_Halbard_01",
					},
					["Improved Charge"] = {
						["Location"] = "2:1",
						["Tooltip"] = "Improved Charge<br>Rank 0/2<br>Requires 5 points in Arms Talents<br>Increases the amount of rage generated by your Charge ability by 3.",
						["Rank"] = "0:2",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_Charge",
					},
					["Sword Specialization"] = {
						["Location"] = "5:4",
						["Tooltip"] = "Sword Specialization<br>Rank 0/5<br>Requires 20 points in Arms Talents<br>Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword.",
						["Rank"] = "0:5",
						["Texture"] = "Interface\\Icons\\INV_Sword_27",
					},
					["Mortal Strike"] = {
						["Location"] = "7:2",
						["Tooltip"] = "Mortal Strike<br>Rank 0/1<br>Requires 1 point in Sweeping Strikes<br>Requires 30 points in Arms Talents<br>30 Rage	5 yd range<br>Instant	6 sec cooldown<br>Requires Melee Weapon<br>A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.",
						["Rank"] = "0:1",
						["Texture"] = "Interface\\Icons\\Ability_Warrior_SavageBlow",
					},
				},
			},
			["Experience"] = "0:0",
			["Sex"] = "Female",
			["DodgePercent"] = "4.00",
			["Skills"] = {
				["Armor Proficiencies"] = {
					["Leather"] = "1:1",
					["Shield"] = "1:1",
					["Mail"] = "1:1",
					["Order"] = 3,
					["Cloth"] = "1:1",
				},
				["Class Skills"] = {
					["Order"] = 1,
					["Arms"] = "1:1",
				},
				["Languages"] = {
					["Order"] = 4,
					["Language: Common"] = "300:300",
				},
				["Weapon Skills"] = {
					["Defense"] = "300:300",
					["Swords"] = "305:305",
					["Order"] = 2,
					["Maces"] = "305:305",
					["Axes"] = "300:300",
					["Unarmed"] = "300:300",
				},
			},
			["ServerTime"] = "19:16",
			["Faction"] = "Alliance",
		},
	},
}
